version: "~> 1.0"
dist: bionic
language: node_js
node_js:
  - 13
branches:
  only:
  - gh-pages
  - /.*/
cache: yarn
install:
  - yarn install
  - yarn global add codecov
script:
  - yarn lint
  - yarn test:ci --coverage
  - codecov
